name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python (if using Python)
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  
    - name: Install dependencies (if using Python)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust according to your dependency file

    - name: Run unit tests (if using Python)
      run: |
        python -m unittest discover -s tests  # Adjust 'tests' to your test directory



    - name: Upload test results (optional)
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: C:\\Users\\nadew\\10x\\week6\\Bati_Bank
